### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by viswanathediga** [sridharchinthaparthi/4studies#1]
Hi i am trying to login but unable to login the site after xampp installation and everything I have done but unable to do it

**Comment by sridharchinthaparthi** [comment]
hi @viswanathediga viswanathediga, you want to create your own database based on the HTML and CSS code in the project and as per your requirements

**Comment by camrionnvmff** [comment]
I saw that you encountered login issues while using XAMPP, and I have also encountered similar situations before, so I completely understand your confusion. According to your description, it seems that you need to create your own database and make some configurations.
You can replace XAMPP with Servbay and directly install the database using Servbay
